// vueexamen/src/components/CreaUsuario.vue
<template>
    <form @submit.prevent="enviaForm()" class="text-center m-4">

    <h1>Crea usuario:</h1>
    <div class="mt-4">
        <label>Introduce tu nombre</label>
        <input type="text" name="cajanombre" v-model="nombre" required>
    </div>
    <div class="mt-4">
        <label>Introduce tu correo</label>
        <input type="text" name="cajaemail" v-model="email" required>
    </div>
    <div class="mt-4 mb-4">
        <label>Introduce tu contraseña</label>
        <input type="password" name="cajapass" v-model="pass" required>
    </div>
    <div class="mt-4 mb-4">
        <label>Repite tu contraseña</label>
        <input type="password" name="cajapass2" v-model="pass2" required>
    </div>
    
    <button>Crea usuario</button>

    </form>

</template>

<script>
    import ServiceUsuario from './../service/ServiceUsuario'
    const service = new ServiceUsuario();

    export default {
        name: "CreaUsuario",
        data(){
            return {
                nombre: "",
                email: "",
                pass:"",
                pass2: ""
            }        
        },
        methods: {
            enviaForm(){
                if (this.pass == this.pass2){
                    var objeto = { "idUsuario":0 , "nombre":this.nombre, "email":this.email, "pass":this.pass}
                    service.insertaUsuario(objeto).then(res => {
                        console.log(res)
                        this.$router.push("/login")
                    })
                }else{
                    alert("No coinciden las contraseñas")
                }
                
            }
        }
    }
</script>

// angularexamen/src/app/components/creausuario/creausuario.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { Usuario } from 'src/app/models/Usuario';
import { Router } from '@angular/router';
import { UsuarioService } from 'src/app/services/usuario.service';

@Component({
  selector: 'app-creausuario',
  templateUrl: './creausuario.component.html',
  styleUrls: ['./creausuario.component.css']
})
export class CreausuarioComponent implements OnInit {

  constructor(private _service: UsuarioService, private _router: Router) { }

  @ViewChild('cajaemail') cajaemail!: ElementRef
  @ViewChild('cajanombre') cajanombre!: ElementRef
  @ViewChild('cajapass') cajapass!: ElementRef
  @ViewChild('cajapass2') cajapass2!: ElementRef

  ngOnInit(): void {
  }

  insertaUsuario(): void {

    if (this.cajapass.nativeElement.value == this.cajapass2.nativeElement.value) {
      var user = new Usuario(
        0,
        this.cajanombre.nativeElement.value,
        this.cajaemail.nativeElement.value,
        this.cajapass.nativeElement.value
      )

      this._service.insertaUsuario(user).subscribe(res => {
        this._router.navigate(["/login"])
      })
      
    }else{
      alert("Las contraseñas no son iguales")
    }

  }

}

<form #formRegister="ngForm" class="text-center m-4">

    <h1>Crea usuario:</h1>
    <div class="mt-4">
        <label>Introduce tu nombre</label>
        <input type="text" #cajanombre name="cajanombre" required>
    </div>
    <div class="mt-4">
        <label>Introduce tu correo</label>
        <input type="text" #cajaemail name="cajaemail" required>
    </div>
    <div class="mt-4 mb-4">
        <label>Introduce tu contraseña</label>
        <input type="password" #cajapass name="cajapass" required>
    </div>
    <div class="mt-4 mb-4">
        <label>Repite tu contraseña</label>
        <input type="password" #cajapass2 name="cajapass2" required>
    </div>
    
    <button (click)="insertaUsuario()">Crea usuario</button>

</form>
