// vueexamen/src/components/RealizaCompra.vue
<template>
    <form class="m-5 p-5 text-center">
    <h1>Insercion de compra</h1>
    <div class="p-3">
        <label>Selecciona un cubo: </label>
        <select name="selectcubo" v-model="cubosel">
            <option v-for="cubo in cubos" :key="cubo" :value="cubo.idCubo">{{cubo.nombre}}</option>
        </select>
    </div>
    <button class="btn btn-success" @click.prevent="realizaCompra()">Realiza compra</button>
    </form>
</template>

<script>

    import ServiceUsuario from './../service/ServiceUsuario'
    const serviceU = new ServiceUsuario();
    import ServiceCubos from './../service/ServiceCubos'
    const serviceC = new ServiceCubos();

    export default {
        name: "RealizaCompra",
        data(){
            return {
                cubos: [],
                cubosel: 1
            }
        },
        methods: {
            realizaCompra(){
                serviceU.realizaCompra(this.cubosel).then(res => {
                    console.log(res);
                    this.$router.push("/detallescompra")
                })
            }
        },
        mounted(){
            serviceC.getCubos().then(res => {
                this.cubos = res
            })
        }
    }
</script>

// angularexamen/src/app/components/realizacompra/realizacompra.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { UsuarioService } from 'src/app/services/usuario.service';
import { Cubo } from 'src/app/models/Cubo';
import { CuboService } from 'src/app/services/cubo.service';

@Component({
  selector: 'app-realizacompra',
  templateUrl: './realizacompra.component.html',
  styleUrls: ['./realizacompra.component.css']
})
export class RealizacompraComponent implements OnInit {

  public cubos!: Array<Cubo>
  @ViewChild("selectcubo") selectcubo!: ElementRef
  
  constructor(private _serviceU: UsuarioService, private _serviceC: CuboService, private _router: Router ) { }

  ngOnInit(): void {

    this._serviceC.getCubos().subscribe(res => {
      this.cubos = res
    })

  }

  realizaCompra(): void {
    console.log(this.selectcubo.nativeElement.value)
    this._serviceU.realizaCompra(parseInt(this.selectcubo.nativeElement.value)).subscribe(res=>{
      this._router.navigate(['/comprasusuario'])
    })
  }

}

<form class="m-5 p-5 text-center" #formCompra="ngForm">
    <h1>Insercion de compra</h1>
    <div class="p-3">
        <label>Selecciona un cubo: </label>
        <select #selectcubo name="selectcubo">
            <option *ngFor="let cubo of cubos" value="{{cubo.idCubo}}">{{cubo.nombre}}</option>
        </select>
    </div>
    <button class="btn btn-success" (click)="realizaCompra()">Realiza compra</button>
</form>
