// vueexamen/src/components/ZonaLogin.vue
<template>
    <form class="text-center m-4" v-on:submit.prevent="sacarToken()">

        <h1>Inicia sesion:</h1>
        <div class="mt-4">
            <label>Introduce tu correo</label>
            <input type="text" name="cajaemail" v-model="email">
        </div>
        <div class="mt-4 mb-4">
            <label>Introduce tu contraseña</label>
            <input type="password" name="cajapass" v-model="password">
        </div>
        
        <button>Iniciar sesion</button>

    </form>
</template>

<script>
    import ServiceUsuario from './../service/ServiceUsuario'
    const service = new ServiceUsuario();

    export default {
        name: "ZonaLogin",
        data(){
            return {
                email: "",
                password: ""
            }
        },
        methods: {
            sacarToken(){
                service.loginUsuario(this.email,this.password).then(res => {
                    localStorage.setItem("token",res.response);
                    this.$router.push("/");
                    /*Tienes que recargar la pagina para ver los apartados una vez logeado*/
                })
            }
        }
    }
</script>

// angularexamen/src/app/components/zonalogin/zonalogin.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { Router } from '@angular/router';
import { Usuario } from 'src/app/models/Usuario';
import { UsuarioService } from 'src/app/services/usuario.service';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-zonalogin',
  templateUrl: './zonalogin.component.html',
  styleUrls: ['./zonalogin.component.css']
})

export class ZonaloginComponent implements OnInit {

  @ViewChild("cajaemail") cajaemail!: ElementRef;
  @ViewChild("cajapass") cajapass!: ElementRef;

  constructor(private _service: UsuarioService, private _router: Router) { }

  ngOnInit(): void {
  }

  iniciaSesion(): void{
    var email = this.cajaemail.nativeElement.value
    var pass = this.cajapass.nativeElement.value
    
    this._service.loginUsuario(email,pass).subscribe(res => {
      environment.token = res.response
      localStorage.setItem("token",res.response);
      this._router.navigate(['/'])
    })
  }

}

<form #formlogin="ngForm" class="text-center m-4">
    <h1>Inicia sesion:</h1>
    <div class="mt-4">
        <label>Introduce tu correo</label>
        <input type="text" #cajaemail name="cajaemail">
    </div>
    <div class="mt-4 mb-4">
        <label>Introduce tu contraseña</label>
        <input type="password" #cajapass name="cajapass">
    </div>
    
    <button (click)="iniciaSesion()">Iniciar sesion</button>

</form>
