// angularexamen/src/app/components/datosusuario/datosusuario.component.ts
import { Component, OnInit } from '@angular/core';
import { Usuario } from 'src/app/models/Usuario';
import { UsuarioService } from 'src/app/services/usuario.service';

@Component({
  selector: 'app-datosusuario',
  templateUrl: './datosusuario.component.html',
  styleUrls: ['./datosusuario.component.css']
})
export class DatosusuarioComponent implements OnInit {

  public usuario!: Usuario;

  constructor(private _service: UsuarioService) { }

  ngOnInit(): void {
    this._service.infoUsuario().subscribe(res => {
      this.usuario = res;
    })
  }

}

<div class="p-5">
    <div *ngIf="usuario" class="w-50 bg-white border border-dark" style="margin-left: 25%;">
        <h3 class="p-3 text-danger">Nombre de usuario: {{usuario.nombre}}</h3>
        <h3 class="p-3 text-primary">Email: {{usuario.email}}</h3>
    </div>
</div>

// vueexamen/src/components/DatosUsuario.vue
<template>
    <div class="p-5">
    <div v-if="usuario" class="w-50 bg-white border border-dark" style="margin-left: 25%;">
        <h3 class="p-3 text-danger">Nombre de usuario: {{usuario.nombre}}</h3>
        <h3 class="p-3 text-primary">Email: {{usuario.email}}</h3>
    </div>
</div>

</template>

<script>

    import ServiceUsuario from './../service/ServiceUsuario'
    const service = new ServiceUsuario();

    export default {
        name: "DatosUsuario",
        data(){
            return {
                usuario: {}
            }
        },
        mounted(){
            service.infoUsuario().then(res => {
                this.usuario = res
            })
        }
    }
</script>
