// angularexamen/src/app/components/detallescubo/detallescubo.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { Cubo } from 'src/app/models/Cubo';
import { Comentario } from 'src/app/models/Comentario';
import { CuboService } from 'src/app/services/cubo.service';

@Component({
  selector: 'app-detallescubo',
  templateUrl: './detallescubo.component.html',
  styleUrls: ['./detallescubo.component.css']
})

export class DetallescuboComponent implements OnInit {

  public cubo!: Cubo;
  public comentarios!: Array<Comentario>;

  constructor(private _service: CuboService, private _activeRoute: ActivatedRoute) { }

  ngOnInit(): void {

    this._activeRoute.params.subscribe((params: Params)=>{

      if(params['id'] != null){

        this._service.getDetallesCubo(parseInt(params['id'])).subscribe(res => {

          this.cubo = res
          
          this._service.getComentariosCubo(this.cubo.idCubo).subscribe(res => {

            if (res.length > 0){
              this.comentarios = res
            }
            
            
          })

        })

      }

    })
  }

}

<div class="w-100 p-5" style="height: 600px;">
    <div class="bg-white w-100" *ngIf="cubo">
        <div class="w-25" style="float: left">
            <img src="{{cubo.imagen}}" width="250px" height="250px"/>
        </div>
        <div class="w-100 bg-warning p-2" height="250px">
            <h1 class="text-center">{{cubo.nombre}}</h1>
            <h6 class="p-2">Marca: {{cubo.marca}}</h6>
            <h6 class="p-2">Modelo: {{cubo.modelo}}</h6>
            <h6 class="p-2">Color: {{cubo.color}}</h6>
            <h6 class="p-2">Precio: {{cubo.precio}}€</h6>
        </div>
    </div>
    <div class="p-5 mt-5 bg-white" *ngIf="comentarios">
        <div class="w-100" *ngFor="let comentario of comentarios">
            <h4>Id-Usuario: {{comentario.idUsuario}}</h4>
            <h4>Fecha: {{comentario.fechaComentario}}</h4>
            <h4>Comentario: {{comentario.comentario}}</h4>
        </div>
    </div>
    <div class="p-5 mt-5 bg-white" *ngIf="!comentarios">
        <h1 class="text-center">Sin comentarios</h1>
    </div>
</div>

// vueexamen/src/components/DetallesCubo.vue
<template>
    <div class="w-100 p-5" style="height: 600px;">
        <div class="bg-white w-100" v-if="cubo">
            <div class="w-25" style="float: left">
                <img :src="cubo.imagen" width="250px" height="250px"/>
            </div>
            <div class="w-100 bg-warning p-2" height="250px">
                <h1 class="text-center">{{cubo.nombre}}</h1>
                <h6 class="p-2">Marca: {{cubo.marca}}</h6>
                <h6 class="p-2">Modelo: {{cubo.modelo}}</h6>
                <h6 class="p-2">Color: {{cubo.color}}</h6>
                <h6 class="p-2">Precio: {{cubo.precio}}€</h6>
            </div>
        </div>
        <div class="p-5 mt-5 bg-white" v-if="comentarios">
            <div class="w-100" v-for="comentario in comentarios" :key="comentario">
                <h4>Id-Usuario: {{comentario.idUsuario}}</h4>
                <h4>Fecha: {{comentario.fechaComentario}}</h4>
                <h4>Comentario: {{comentario.comentario}}</h4>
            </div>
        </div>
    </div>
</template>

<script>

    import ServiceCubos from './../service/ServiceCubos';
    const service = new ServiceCubos();

    export default {
        name: "DetallesCubo",
        data(){
            return {
                comentarios: [],
                cubo: {}
            }
        },
        mounted(){
            if (this.$route.params.id != undefined){
                service.getDetallesCubo(this.$route.params.id).then(res => {
                    this.cubo = res
                    service.getComentariosCubo(this.$route.params.id).then(res => {
                        this.comentarios = res
                        console.log(this.cubo)
                    })
                })
            }
        }
    }
</script>
