// vueexamen/src/components/DetallesCompra.vue
<template>
    <div class="w-100 p-5" style="height: 600px;">
    <div class="p-5 bg-white" v-if="compras">
        <div class="w-100 p-5 mt-5 border border-dark" v-for="compra in compras" :key="compra">
            <h4>ID de cubo comprado: {{compra.idCubo}}</h4>
            <h4>ID del pedido: {{compra.idPedido}}</h4>
            <h4>Fecha de compra: {{compra.fechaPedido}}</h4>
        </div>
    </div>
</div>

</template>

<script>

    import ServiceUsuario from './../service/ServiceUsuario'
    const service = new ServiceUsuario();

    export default {
        name: "DetallesCompra",
        data(){
            return {
                compras: []
            }
        },
        mounted(){
            service.infoCompras().then(res => {
                this.compras = res
            })
        }
    }
</script>

// angularexamen/src/app/components/detallescompra/detallescompra.component.ts
import { Component, OnInit } from '@angular/core';
import { Compra } from 'src/app/models/Compra';
import { UsuarioService } from 'src/app/services/usuario.service';

@Component({
  selector: 'app-detallescompra',
  templateUrl: './detallescompra.component.html',
  styleUrls: ['./detallescompra.component.css']
})
export class DetallescompraComponent implements OnInit {

  public compras!: Array<Compra>

  constructor(private _service: UsuarioService) { }

  ngOnInit(): void {
    this._service.infoCompras().subscribe(res => {
      this.compras = res
    })
  }

}

<div class="w-100 p-5" style="height: 600px;">
    <div class="p-5 bg-white" *ngIf="compras">
        <div class="w-100 p-5 mt-5 border border-dark" *ngFor="let compra of compras">
            <h4>ID de cubo comprado: {{compra.idCubo}}</h4>
            <h4>ID del pedido: {{compra.idPedido}}</h4>
            <h4>Fecha de compra: {{compra.fechaPedido}}</h4>
        </div>
    </div>
</div>
